services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements-bot.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    envVarsOverrides:
      PYTHON_VERSION: 3.11.9
